### ISSUE TITLE
Рефакторинг MD5Utils

### ISSUE THREAD

**Issue by AntipovAndrey** [birdy-messenger/Android-client#4]
https://github.com/birdy-messenger/Android-client/blob/master/app/src/main/java/com/birdyteam/birdyandroidversion/hash/MD5Utils.kt

1. Превратить метод в функцию-расширение над ```String```
2. Переделать сам метод - убрать try-catch, lateinit, while

**Comment by Aroize** [comment]
Зарефакторено + пройдены Unit тесты
